### ISSUE TITLE
Estimated release date?

### ISSUE THREAD

**Issue by sergiobdrl** [Jumpat/SegAnyGAussians#1]
Omg! This is a great tool for the community. Is there an estimated release date for the code?

**Comment by Jumpat** [comment]
The code will be released within this month. Thanks for your interest!

**Comment by Daviddddl** [comment]
mark

**Comment by yiku-bit** [comment]
Very much looking forward to it, too.

**Comment by Jumpat** [comment]
The code has been released and the detailed instruction will be fully released in the next week, since I'm occupied by many other issues recently.
