### ISSUE TITLE
The training loss is Nan

### ISSUE THREAD

**Issue by zhirui-gao** [Jumpat/SegAnyGAussians#105]
Training progress:   2%|▏         | 160/10000 [00:11<11:33, 14.19it/s, RFN=nan, Pos cos=nan, Neg cos=nan, Loss=nan]

I followed the instructions in the readme and tested the code in the DTU dataset, but the training loss rapidly became nan.

**Comment by Jumpat** [comment]
Hi, I doubt this is caused by the empty background of DTU. We have not tested our code on DTU dataset. It may require additional process.

**Comment by zhirui-gao** [comment]
Thanks for your reply!
