### ISSUE TITLE
how to get 3d gaussian splat labels 

### ISSUE THREAD

**Issue by xuyanging** [Jumpat/SegAnyGAussians#108]
Hello, how do you know which Gaussian balls belong to the same category in 3D space. 

For example, if a trained model has three million Gaussian balls, there is a way to generate a label of [three million, 1] when inferring, and the corresponding Gaussian balls of the same number are grouped into a cluster, representing that these Gaussian balls are of the same object in 3D space.

**Comment by Jumpat** [comment]
SAGA follows an interactive pipeline, with input prompts (points, in practice), SAGA converts them into query features. These query features can be used to measuring feature similarities between each 3D Gaussian. Then, a feature threshold is used to split the 3D Gaussians into foreground and background.
