### ISSUE TITLE
If use language-driven segmentation, load clip feature and original masks

### ISSUE THREAD

**Issue by Lydiatingting** [Jumpat/SegAnyGAussians#117]
Hello, I see the following comment in the "# Data and Model Preparation" section of the "**prompt_segmenting.ipynb**" file: "**# If use language-driven segmentation, load clip feature and original masks"**. If I need to use **language-driven segmentation**, what adjustments should I make to the code?
 **I would greatly appreciate your response.**

**Comment by Jumpat** [comment]
Hi. The comment may be a little misleading. If you want to use language feature, you only need to set the following dataset.need_features = True

**Comment by Lydiatingting** [comment]
thank you!
I'll give it a try right away
