### ISSUE TITLE
output the segmentated model

### ISSUE THREAD

**Issue by xiaoxiaoqiang9527** [Jumpat/SegAnyGAussians#12]
Thank you for open-sourcing your codes，I am a newbie and I am reproducing the code given. I found that the final output results are rendered pictures. Where can I find the 3D model obtained after segmentation? Looking forward to your reply.

**Comment by Jumpat** [comment]
Hello, the binary segmentation mask is stored in segmentation_res/final_mask.pt

**Comment by xiaoxiaoqiang9527** [comment]
> Hello, the binary segmentation mask is stored in segmentation_res/final_mask.pt

Thanks

**Comment by xiaoxiaoqiang9527** [comment]
With these masks, do I need to write additional code to reconstruct the original Gaussian out of the segmentation result?

**Comment by xiaoxiaoqiang9527** [comment]
Sorry to interrupt again, but how can I present these 3D segmentation results, as in the example video, showing the original 3D scene and a part obtained after segmentation?

**Comment by Jumpat** [comment]
Hello, these instructions are presented in our README.md (refer to the rendering)

**Comment by xiaoxiaoqiang9527** [comment]
> Hello, these instructions are presented in our README.md (refer to the rendering)
Thank you very much for your reply, I will read and learn from it, thanks again!

**Comment by xiaoxiaoqiang9527** [comment]
> Hello, these instructions are presented in our README.md (refer to the rendering)

Thank you very much for your reply, I will read and learn from it, thanks again!

**Comment by xiaoxiaoqiang9527** [comment]
I'm very sorry to bother you again, but I'm rusty and my teacher keeps pushing. I would like to ask you, I followed the first step of rendering to get a lot of picture results of garden, how do I come up with the final 3d model? I apologize for asking you these stupid questions.

**Comment by Jumpat** [comment]
That's okay my friend. I wonder what kind of 3D model do you need? The 'segmentation_res/final_mask.pt' file is the segmented  mask for Gaussians. By removing the background you can get the 3D object represented by 3D Gaussians (you can check [here](https://github.com/Jumpat/SegAnyGAussians/blob/5142b1ab1e098b2fef191feeee8113b2fc2be137/scene/gaussian_model.py#L335C9-L335C16) for more details).

**Comment by xiaoxiaoqiang9527** [comment]
I'm actually not sure, haha, my teacher told me to reproduce all of them over the past few days, but I'm not sure what he wants me to do, and I've never dabbled in any of this stuff before. Thank you very much for your answer.

**Comment by Jumpat** [comment]
You're welcome. If you have more information/questions just ask here.

**Comment by xiaoxiaoqiang9527** [comment]
Hello, what software are you using for visualization?

**Comment by norton-swz** [comment]
It seems possible to use SIBR_gaussianViewer_app in gaussian-splatting, but needs to rename seg_no_mask_point_cloud.ply to point_cloud.ply.

**Comment by cs-mshah** [comment]
You can try viewing your `.ply` files in https://github.com/playcanvas/super-splat by locally running it.
