### ISSUE TITLE
What is this Camera save action using for?

### ISSUE THREAD

**Issue by Matt-V50** [Jumpat/SegAnyGAussians#122]
https://github.com/Jumpat/SegAnyGAussians/blob/96e5021f2544af95e7705f91ecd8db6bb5cba381/scene/__init__.py#L121

Just curious why you covert the `R,T` matrix. Seems you didn't use it anywhere else.

**Comment by Matt-V50** [comment]
Found a relative explanation.

https://github.com/graphdeco-inria/gaussian-splatting/issues/509#issuecomment-2290932322

**Comment by Jumpat** [comment]
Yeah I just re-use the 3D-GS code.😂
