### ISSUE TITLE
关于交互方式

### ISSUE THREAD

**Issue by HanLingsgjk** [Jumpat/SegAnyGAussians#14]
老哥，首先你这个工作做的是真的吊，很有意义，试了一下效果可以的。

我发现jupyter 里面的交互是直接代码指定一个点

如果我想多个点，或者框子，或者涂鸦，来做交互。
大佬您有什么建议吗？

**Comment by Jumpat** [comment]
你好！👋
目前我们暂没有实现SAGA的交互式界面（主要是由于Gaussian Splatting的GUI代码复杂，修改困难），但SAM本身支持多种类型的输入提示词，例如bounding box，scribble可以转换为多个点来作为对SAM的输入，进而可以通过SAM输出的mask来进行分割。

**Comment by Jumpat** [comment]
> * How to Automatically Generating Object Masks with SAM? Like below.
>   ![image](https://private-user-images.githubusercontent.com/33644565/310729686-9e0b95f1-b03c-4b56-a496-dfe2b4517d15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODgxMDUsIm5iZiI6MTcwOTc4NzgwNSwicGF0aCI6Ii8zMzY0NDU2NS8zMTA3Mjk2ODYtOWUwYjk1ZjEtYjAzYy00YjU2LWE0OTYtZGZlMmI0NTE3ZDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA1MDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWFiYWU5MGVjNGEyMzEzZWUwYTM2ZGFkMDJlNzU4MTMxOGU4MDZmYzE4YzNiNGEzYjkzYTYyZWQzZmEzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwnBCZ7HPpPtxVdAG5HqT0WbtoeZYt-wJMdriBVbdiE)
>   ![image](https://private-user-images.githubusercontent.com/33644565/310729945-41625308-e214-495d-952f-0e9d4fc17c90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODgxMDUsIm5iZiI6MTcwOTc4NzgwNSwicGF0aCI6Ii8zMzY0NDU2NS8zMTA3Mjk5NDUtNDE2MjUzMDgtZTIxNC00OTVkLTk1MmYtMGU5ZDRmYzE3YzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA1MDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmQ2MzU2NWM3Mzg1ZmQyNzRkNjYzZDFmMjI1MWY5MjE1YTc1ODAzYzkxNDUzYTFjMDVjODAzZjJjNmQ5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kg2XtvczhVVFgJ12a1Unrk3tUXSObmHhzXxlBAvjGms)
> * For point prompt, how to obtain the point coordinate?

Hello, you can find these information [here](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb)
