### ISSUE TITLE
extract_features.py: error: unrecognized arguments: --downsample 4

### ISSUE THREAD

**Issue by wyysteelhead** [Jumpat/SegAnyGAussians#15]
I followed the readme template to use  extract_features.py, as below:
`python extract_features.py --image_root xxx --sam_checkpoint_path xxx --downsample 4`
but an error occured:
`extract_features.py: error: unrecognized arguments: --downsample 4`

**Comment by Jumpat** [comment]
Hello! Sorry for the misleading. Extracting features does not use too much GPU memory thus we omit the downsample arg. Just ignore it.

**Comment by wyysteelhead** [comment]
> Hello! Sorry for the misleading. Extracting features does not use too much GPU memory thus we omit the downsample arg. Just ignore it.

Can I use --downsample when running "extract_segment_everything_masks.py" while extracting features without down sampling? Because running extract_segment_everything_masks.py is taking to much time on my card :(

**Comment by Jumpat** [comment]
Yes! I checked the code and the downsample is available in extracting masks.
