### ISSUE TITLE
Some questions about Gaussian Splatting for segmentation

### ISSUE THREAD

**Issue by xiaoxiaoqiang9527** [Jumpat/SegAnyGAussians#16]
Sorry to bother you again. I do not know much about gaussian splatting, but my boss/teacher asks me: Why does 3D everything segmentation nowadays involve 2D SAM and not go straight to 3D segmentation of everything? I hope you can give me some tips or guidance for further research. Looking forward to your comments! Thanks!

**Comment by xiaoxiaoqiang9527** [comment]
Maybe it's a matter of not enough data? but maybe there are other reasons too?

**Comment by Jumpat** [comment]
Data is the most problematic thing. Then the modal of 3D data also makes it hard to train a universal segmentor. Last but not least, I think segmentation in 2D is more intuitive than 3D. The way human segment 3D object is just similar like SA3D (you can refer to that paper for more details).

**Comment by xiaoxiaoqiang9527** [comment]
Okay, I'll keep trying to learn. Thank you very much for such a prompt reply, much appreciated!
