### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args'

### ISSUE THREAD

**Issue by Liumomo30** [Jumpat/SegAnyGAussians#18]
FileNotFoundError: [Errno 2] No such file or directory: '/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args',我的文件夹中只有cfg_args，请问seg_cfg_args是在哪个步骤中生成的吗

**Comment by Liumomo30** [comment]
python render.py -m /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/ --precomputed_mask /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/segmentation_res/crack/final_mask.pt --target seg
Looking for config file in /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args
Traceback (most recent call last):
  File "render.py", line 117, in <module>
    args = get_combined_args(parser)
  File "/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/arguments/__init__.py", line 122, in get_combined_args
    with open(cfgfilepath) as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: '/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args'

**Comment by Liumomo30** [comment]
python render.py -m /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/ --precomputed_mask /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/segmentation_res/crack/final_mask.pt --target seg

Looking for config file in /media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args
Traceback (most recent call last):
  File "render.py", line 117, in <module>
    args = get_combined_args(parser)
  File "/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/arguments/__init__.py", line 122, in get_combined_args
    with open(cfgfilepath) as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: '/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/seg_cfg_args'

**Comment by Jumpat** [comment]
你好！这里的错误是因为一些代码上尚未完全修改好的漏洞。请将target设置为scene，并使用--segment来获得最后的分割结果。

**Comment by Liumomo30** [comment]
你好，打扰了。运行结束后/media/liumomo/EXTERNAL_USB/NerF/SegAnyGAussians-main/output/crack/train/ours_30000下有gt、mask、renders三个文件夹，然而mask却是空的，是不是不正常呢

**Comment by Jumpat** [comment]
这是正常的，在这个渲染选项下移除了场景中其他物体，因此无法生成对应的二维mask

**Comment by Liumomo30** [comment]
感谢您的回复，请问要做量化的话，有办法导出二维掩码图嘛

**Comment by Jumpat** [comment]
你好，是可以的，在prompt_segmenting.ipynb文件的最后，我们给出了渲染mask的代码。
