### ISSUE TITLE
How can I accelerate extract_segment_everything_masks.py ? 

### ISSUE THREAD

**Issue by wyysteelhead** [Jumpat/SegAnyGAussians#21]
我尝试着在一个约有300张图片的数据集上运行extract_segment_everything_masks.py，需要大约22分钟，但是这些照片在用于3dgs重建时并不需要这么长的时间，导致prepare data的时间比重建的时间还长了。
所以我想问一下是否有加速extract_segment_everything_masks.py的方法？降低一些精度也可以。（图像的downsample似乎无法加速这一过程）

**Comment by Jumpat** [comment]
你好，mask extraction部分的耗时主要是由SAM的automatic mask generator设计决定的。

我目前能想到两种解决方案来加速这一过程：

第一种方式，对数据集进行稀疏采样，比如只使用五分之一的数据进行特征场训练（相邻帧之间往往存在大量冗余信息，因此抽帧是比较合理的setting）；

第二种方式，调节mask auto extractor的超参数，具体请参考SAM的说明文档，对超参数的调节可以在extract_segment_everything_masks.py这个文件中进行修改来实现。

**Comment by wyysteelhead** [comment]
好的，非常感谢！
