### ISSUE TITLE
How to crop out an object in a pretrained 3d gaussian model

### ISSUE THREAD

**Issue by LaFeuilleMorte** [Jumpat/SegAnyGAussians#22]
Thanks for you brilliant work. I was wondering if this method could clip the object out of a 3d gaussian point clouds? For example. If I want to get a clean object and remove all its backgrounds from a pretrained gaussian model, is it able to extract the gaussian splats which belongs to the object, and remove all splats that belong to its background?

**Comment by Jumpat** [comment]
Hello! Thanks for your interest! This has been realized in the [gaussian_model.py](https://github.com/Jumpat/SegAnyGAussians/blob/main/scene/gaussian_model.py). Please check the segment() function.
