### ISSUE TITLE
how to use custom data??

### ISSUE THREAD

**Issue by hanjoonwon** [Jumpat/SegAnyGAussians#27]
If I want to write about my own custom images, how do I process them? Can I do what I did with gssplat?

**Comment by Jumpat** [comment]
Yes, the data preparation process is just the same as 3DGS.

**Comment by hanjoonwon** [comment]
> Yes, the data preparation process is just the same as 3DGS.

If so, if I already have 3DGS in my CONDA environment, would it be okay to run it in that environment instead of creating a new environment for this repository?

**Comment by Jumpat** [comment]
Yeah, you can directly install the additional dependencies in it.

**Comment by hanjoonwon** [comment]
> Yeah, you can directly install the additional dependencies in it.

sorry, I'm new to this so have question.

i trained with these.
python extract_features.py --image_root imgs/owl --sam_checkpoint_path dependencies/sam_vit_h_4b8939.pth --downsample 4
python extract_segment_everything_masks.py  --image_root imgs/owl --sam_checkpoint_path dependencies/sam_vit_h_4b8939.pth --downsample 4
python train_scene.py -s   gsdata/owl2
python train_contrastive_feature.py -m output/ad3718d0-8


After these steps, what if I want to apply it to a sugar model?? Do I need to do the segmentation ipynb file as well?

**Comment by Jumpat** [comment]
Hi, SAGA requires to re-train the 3D features for each different scene.

**Comment by jiachen0212** [comment]
> Hi, SAGA requires to re-train the 3D features for each different scene.

I used the colmap format obtained by nerfstudio, and the obtained trans.json was executed according to the author's training steps, but I encountered this error. Can you explain it? ~

**Comment by hanjoonwon** [comment]
> > Hi, SAGA requires to re-train the 3D features for each different scene.
> 
> I used the colmap format obtained by nerfstudio, and the obtained trans.json was executed according to the author's training steps, but I encountered this error. Can you explain it? ~

You should use convert.py provided in this repository. That fixed the error for me too
