### ISSUE TITLE
Can we directly compute out the 3D segmentation without iterative fitting?

### ISSUE THREAD

**Issue by yuedajiong** [Jumpat/SegAnyGAussians#3]
1.  do 2d segmentaion(2-category/01, or object-by-object),  one-time
2.  all pixels in 2D space, can be mapped matched GS points in 3D space.  (refer:  GS renderer inside)

faster?

**Comment by Jumpat** [comment]
Hello! Yeah, but by this way, the masks in different views indicating the same object must be identified by another mechanism, which, in SAGA, is the contrastive-style training.

**Comment by yuedajiong** [comment]
thanks, keep in my mind.

**Comment by Jumpat** [comment]
Sorry for the late, the detailed instruction will be fully released in the next week, since I'm occupied by many other issues recently.
