### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by hanjoonwon** [Jumpat/SegAnyGAussians#30]
![image](https://github.com/Jumpat/SegAnyGAussians/assets/125524043/851464e3-f6c8-4ca5-8eab-305d5ea055a2)

when i try to use python train_scene.py -s got this error

**Comment by jiachen0212** [comment]
> ![image](https://private-user-images.githubusercontent.com/125524043/311424912-851464e3-f6c8-4ca5-8eab-305d5ea055a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzc5NDQsIm5iZiI6MTcxMDEzNzY0NCwicGF0aCI6Ii8xMjU1MjQwNDMvMzExNDI0OTEyLTg1MTQ2NGUzLWY2YzgtNGNhNS04ZWFiLTMwNWQ1ZWEwNTVhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwNjE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY2MjlkYjhhODA3ZDQ3NzU2NGRhYTFiNDkxNmMxNGVmNjFlOWFhYWEyZjA0M2UwMTZkMDNjMTQyNmQ5ZmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7MrnqgUifL4BTL1eTexpZF7d7hq5AGqAEN8HNgCXbA)
> 
> when i try to use python train_scene.py -s got this error

i also get the same bug, you may need change zhe code~

**Comment by Jumpat** [comment]
Hi, do you use the diff-rasterizer provided by 3DGS? Please use our provided one in the submodule.

**Comment by hanjoonwon** [comment]
> Hi, do you use the diff-rasterizer provided by 3DGS? Please use our provided one in the submodule.
@Jumpat 
i use this python /home/xiangyue/joonwon/SegAnyGAussians/convert.py  -s /home/xiangyue/joonwon/SegAnyGAussians/imgs/owl/  but i got that eerror

**Comment by hanjoonwon** [comment]
> Hi, do you use the diff-rasterizer provided by 3DGS? Please use our provided one in the submodule.

yes i use python /home/xiangyue/joonwon/SegAnyGAussians/convert.py  -s /home/xiangyue/joonwon/SegAnyGAussians/imgs/owl/ 
but got that error  @Jumpat

**Comment by Jumpat** [comment]
There must be some misunderstood, since the convert.py does not involve the rendering and thus it should not report such error. The convert.py is only a script that calls the colmap for image processing.

**Comment by hanjoonwon** [comment]
> There must be some misunderstanding, since the convert.py does not involve the rendering and thus it should not report such error. The convert.py is only a script that calls the colmap for image processing.

I'll try again thanks

**Comment by hanjoonwon** [comment]
> There must be some misunderstanding, since the convert.py does not involve the rendering and thus it should not report such error. The convert.py is only a script that calls the colmap for image processing.

I set the environment to overwrite the existing gs3d environment, so I guess I did something wrong there, thanks.
