### ISSUE TITLE
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]

### ISSUE THREAD

**Issue by xiaoxiaoqiang9527** [Jumpat/SegAnyGAussians#41]
您好，我在使用nerf_Synthetic数据集训练Gaussian时遇到了这个问题
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]。
我在Gaussian splatting的issues里找了一下没有具体解决措施，请问您有遇到过并解决吗？

**Comment by Jumpat** [comment]
你好，有没有尝试过用原始的3dgs代码来训练？实际上saga写的时候没有考虑nerf_synthetic这个数据集，dataloader也没考虑这个，可能是我们对高斯和渲染器的一些改动导致了这个问题

**Comment by Jumpat** [comment]
Hi，这个功能是由Gaussian Splatting提供的SH_to_RGB函数提供的。

**Comment by xiaoxiaoqiang9527** [comment]
抱歉再次打扰，我只找到了utils.sh_utils下的RGB2SH，请问是在哪个文件里有这个函数呢。

**Comment by Jumpat** [comment]
可以通过反转这个函数来获得RGB值：
```
def SH2RGB(sh):
    return sh * C0 + 0.5
```

**Comment by xiaoxiaoqiang9527** [comment]
好的，抱歉我没自己去多想，我试一下

**Comment by xiaoxiaoqiang9527** [comment]
hhh，不好意思，我没看函数定义 0.o，十分抱歉

**Comment by xiaoxiaoqiang9527** [comment]
谢谢，sh的参数应该是f_dc和f_rest吗

**Comment by Xjianen** [comment]
> 您好，我在使用nerf_Synthetic数据集训练Gaussian时遇到了这个问题 RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]。 我在Gaussian splatting的issues里找了一下没有具体解决措施，请问您有遇到过并解决吗？

您好，我最近想用无纹理的mesh实现3DGS时，也遇见了这个问题，请问你是怎么解决的？谢谢！
