### ISSUE TITLE
Questions about 3D Gaussian training

### ISSUE THREAD

**Issue by sugerkiller** [Jumpat/SegAnyGAussians#42]
Thank you very much for your open source code, I have learned a lot，But when I was training the leaves data set in the NERF-LLFF data set, I encountered that colmap could not estimate the correct pose and the camera matrix could not be created. I would like to ask if you have encountered similar problems.
```
==============================================================================
Finding good initial image pair
==============================================================================

  => No good initial image pair found.

Elapsed time: 0.754 [minutes]
ERROR: failed to create sparse model
```

**Comment by Jumpat** [comment]
Hi. LLFF-leaves? Or other scene? I once met similar problem in LLFF-leaves and have to use the provided colmap results rather than re-processing it.

**Comment by sugerkiller** [comment]
@Jumpat yes ，LLFF-leaves scene，The camera matrix provided by llff and the camera matrix generated by colmap have different numerical arrangement. I am not sure how to use the camera matrix provided by llff to train the 3dgs model

**Comment by Jumpat** [comment]
I think the dataset_reader of SAGA has supported loading llff. Check[here](https://github.com/Jumpat/SegAnyGAussians/blob/5142b1ab1e098b2fef191feeee8113b2fc2be137/scene/dataset_readers.py#L99).

**Comment by sugerkiller** [comment]
Thank you for your generous answer！！
