### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by shenqianxiang** [Jumpat/SegAnyGAussians#46]
我在运行prompt_segmenting时 第三个框框的时候
![QQ图片20240418084801](https://github.com/Jumpat/SegAnyGAussians/assets/167383249/6e741be4-d395-486a-8895-ab62cbb630c5)
出现了问题

**Comment by shenqianxiang** [comment]
我用的是360_v2的garden

**Comment by Jumpat** [comment]
你好，根据[这行代码](https://github.com/Jumpat/SegAnyGAussians/blob/5142b1ab1e098b2fef191feeee8113b2fc2be137/scene/__init__.py#L97)，请检查cfg_args中的数据集路径是否发生了变化，和当前数据集位置不一致。

**Comment by shenqianxiang** [comment]
哦哦 我之前是在另一个电脑跑的 路径确实不一样 谢谢作者
