### ISSUE TITLE
球协函数转RGB

### ISSUE THREAD

**Issue by xiaoxiaoqiang9527** [Jumpat/SegAnyGAussians#49]
抱歉再次打扰，上次询问您嘞SH2RGB的问题。近期我试了一下效果，但是转换结果和您论文中的有差距，请问是不是哪里处理不对？
![paper](https://github.com/Jumpat/SegAnyGAussians/assets/67455751/f7d2351b-2aa0-4b78-966d-039935d493b1)
对于这个场景，我读取了ply里的f_dc_0，f_dc_1，f_dc_2，将其传入了SH2RGB函数，结果作为rgb存入ply，最终用Viewer可视结果如下：
![viewer_room](https://github.com/Jumpat/SegAnyGAussians/assets/67455751/fc3572ec-8386-4a67-82d5-b3cce5cbe1ef)
cloud_compare结果为：
![image](https://github.com/Jumpat/SegAnyGAussians/assets/67455751/97c59bd4-5934-499c-9fd3-c064deaa8d53)

**Comment by Jumpat** [comment]
你好这可能是由于可视化软件的不同导致的，我们进行可视化时使用的是meshlab，可以使用meshlab再试试

**Comment by xiaoxiaoqiang9527** [comment]
您好，meshlab查看效果是这样的：
![image](https://github.com/Jumpat/SegAnyGAussians/assets/67455751/315eafa3-628f-42b9-a1c3-6a1f97081d09)
是不是要对sh或者rgb进一步处理呢，因为sh包含负值，转换为rgb后仍然存在负值

**Comment by Jumpat** [comment]
<img width="442" alt="image" src="https://github.com/Jumpat/SegAnyGAussians/assets/49474962/5fcdd753-82ea-45ac-a003-54479c633f56">
可能是点的颜色配置不同导致的，检查一下这里看看。我们之前是没有进行其他处理的。

**Comment by xiaoxiaoqiang9527** [comment]
![image](https://github.com/Jumpat/SegAnyGAussians/assets/67455751/5fa834a3-f92f-4517-acf8-7beeb78e558f)
结果还是一样的。那或许是我的场景ply出了问题吗

**Comment by Jumpat** [comment]
可以把小于0大于255的RGB值裁剪一下试试，把背景换成白色，再调节一下点的size应该就能达到一样的效果了

**Comment by xiaoxiaoqiang9527** [comment]
> ![image](https://private-user-images.githubusercontent.com/33644565/326953939-d44e74e1-4bb2-46c6-9ac3-4c621826205e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5Nzk0NTQsIm5iZiI6MTcxNDk3OTE1NCwicGF0aCI6Ii8zMzY0NDU2NS8zMjY5NTM5MzktZDQ0ZTc0ZTEtNGJiMi00NmM2LTlhYzMtNGM2MjE4MjYyMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA3MDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZjM3YmQyMjI4MDQzMzUzMjE3YWZmMWY5ZWY3NjJkZTllMjM3YjcyNzQzNGFhMGMwOTNhNGQ3MzAxMzBhYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYrvO5oFnZxr5d_Hm4J6tDPDqkklyRwUtKWc5_C_5TE)
> 
> 除了f_dc_0，f_dc_1，f_dc_2这三个参数外，其他很多参数都和颜色有关系吧？ 我是从super splat直接看的3DGS模型。

对的，但是我看sh2rgb的参数应该是N*3的，就把dc_012传入了
