### ISSUE TITLE
关于环境的安装

### ISSUE THREAD

**Issue by king1111sadjfoisja** [Jumpat/SegAnyGAussians#51]
亲爱的作者您好，非常感谢您开源这么伟大的一篇论文，本人在安装环境是，遇到了以下错误：
![image](https://github.com/Jumpat/SegAnyGAussians/assets/145326984/adb3f7dd-77e7-46c2-9487-24c04cb555bb)
想问下您有无解决方案，再次感谢！！！

**Comment by king1111sadjfoisja** [comment]
解决了谢谢

**Comment by dingxusen** [comment]
> 解决了谢谢
您好，请问一下您怎么解决的，我也在这里出了问题，非常感谢
