### ISSUE TITLE
关于如何分割出自己想要的物体。

### ISSUE THREAD

**Issue by wikiwa** [Jumpat/SegAnyGAussians#53]
作者，您好。您的SAGA让我受益匪浅。我这里有个问题想要问您，我该如何去通过SAGA分割得到自己想要的物体，就比如说我想从bicycle场景中分割得到自行车或者是自行车的轮胎。

**Comment by Jumpat** [comment]
你好，这个功能在prompt_segment.ipynb这个notebook文件中实现
