### ISSUE TITLE
训练3D高斯的过程

### ISSUE THREAD

**Issue by king1111sadjfoisja** [Jumpat/SegAnyGAussians#54]
尊敬的作者您好！感谢您开源如此伟大的项目
我在预训练3D高斯的时候遇到了下面这个问题：
![image](https://github.com/Jumpat/SegAnyGAussians/assets/145326984/a4625b4f-b575-4278-8b6c-8e5b4646822c)
就是他这个training progress怎么只训练到23％就结束了？

**Comment by Jumpat** [comment]
你好，谬赞
这里并没有结束训练，只是保存了训练过程中间的ckpt

**Comment by king1111sadjfoisja** [comment]
谢谢我哥

**Comment by king1111sadjfoisja** [comment]
您好，还有个问题就是：
![image](https://github.com/Jumpat/SegAnyGAussians/assets/145326984/cc6ffc16-6345-4fc5-be65-eb57d3467f67)
在预训练完3D高斯之后，应该进行3D高斯特征的训练，这里要指明<path to the pre-trained 3DGS model>，但我预训练结束后output文件夹中出现了两个文件夹，此时我应该怎么填这个路径呢？期待您的回复！
