### ISSUE TITLE
3DGS model quality 

### ISSUE THREAD

**Issue by Lizhinwafu** [Jumpat/SegAnyGAussians#57]

**Comment by Jumpat** [comment]
> ![image](https://private-user-images.githubusercontent.com/33644565/331449955-365f62bc-1b86-4c94-865e-002d644204fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTU2MzksIm5iZiI6MTcxNjQ1NTMzOSwicGF0aCI6Ii8zMzY0NDU2NS8zMzE0NDk5NTUtMzY1ZjYyYmMtMWI4Ni00Yzk0LTg2NWUtMDAyZDY0NDIwNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA5MDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODJmNDdjZjg5MGE2NjBiMDRhY2M0NzAyOGUwMDZhMWEyZDExMWIxNjE5NjU2YjQ5MjU1Y2MzNDc2NDEyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h1qI7uL7o2fEALasFwIqj8HyG-TvIM2QhT4ht68IPHY)
> 
> ![image](https://private-user-images.githubusercontent.com/33644565/331449977-3a34c440-becd-4822-893f-20439f970696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTU2MzksIm5iZiI6MTcxNjQ1NTMzOSwicGF0aCI6Ii8zMzY0NDU2NS8zMzE0NDk5NzctM2EzNGM0NDAtYmVjZC00ODIyLTg5M2YtMjA0MzlmOTcwNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA5MDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ODYzMjM4YzNmMGVjNWI0M2FkYmY4NjMyZjQyNzFhYzUxMTUyODU4NjI1MzQ2OTU5ZTU3NWJjM2VjNDBmOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laSePHVQX6irIag-0Qqb0Vcomno_nJ2bJ_JsIJ-4Eu0)
> 
> The above is the model trained by Polycam, and the following is the model training result provided by SAGA. Why is the quality so different?

The quality of SAGA is determined by the reconstruction quality of 3D-GS.



> For others, I found that when giving prompt points, SA3D acts on the rendered 2D image of the NeRF model, and SAGA acts on the training 2D image. Why is there such a difference?

There is almost no difference between the two implementation.
