### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by zw20130717** [Jumpat/SegAnyGAussians#58]
when i ran extract_features.py using the command in github page, i was informed cuda out of memory. I'm new to coding and python project. After searching the Internet, I changed the batch_size and downsample and still was unable to solve the problem. The imgs I used was 1074*544. Befor SAGA I had successfully run the 3DGS project and received no error information. Can anyone offer any advice which i will be very appreciated (except for change of hardware)
![2024-05-23 17-04-49 的屏幕截图](https://github.com/Jumpat/SegAnyGAussians/assets/166890502/b4efe889-ba24-4f87-9c96-e7d6c4335809)

**Comment by Jumpat** [comment]
Hi you may need 24GB GPU memory for training SAGA. SAGA attaches additional features to the original GS model and the training requires more memory

**Comment by zw20130717** [comment]
> Hi you may need 24GB GPU memory for training SAGA. SAGA attaches additional features to the original GS model and the training requires more memory

omg 24GB. I presume this is way beyond the efforts of code changing and image editting to solve this cuda-out-of-memory problem. Anyway, thanks for your reply. I may have to borrow someone else's computer to run this project.

**Comment by Jumpat** [comment]
You're welcome. We are using a 3090. There may be some method to cut down GPU consumption. For example you can move the sam_masks to cpu. Or you can downsample the masks for supervision, or sample some masks (do not use all masks in an iteration of training). You can check it by yourself.

**Comment by Luca-Wiehe** [comment]
In the `v2`-version of the project, I have the same problem despite having 24GB of GPU memory. I trained SAM masks using the `--downsample 4` flag. 

Since you have the same GPU limitations that we have, which downsampling factor did you use for SAM masks? Did you do anything else to reduce GPU requirements?
