### ISSUE TITLE
Segment-Everything Results

### ISSUE THREAD

**Issue by Luca-Wiehe** [Jumpat/SegAnyGAussians#59]
In your paper in section 4.2.2., you visualize segmentation results for full scenes. I ran the `prompt_segmenting.ipynb`-notebook where segmentation is performed solely based on specified input points. 

Is there a way to segment full scenes with your provided codebase or are there some unpublished code parts that would be required for that task?

**Comment by Jumpat** [comment]
Hi, thanks for your interest.

The current code is different from the arXiv paper. We are working on the new version currently and hope to release it with a more flexible GUI.

**Comment by Luca-Wiehe** [comment]
Is there a rough estimate of how long this may take?

**Comment by Jumpat** [comment]
I'm not sure. I hope to finish this project next week. If it's slower, it might take about two weeks.
