### ISSUE TITLE
How to obtain panoptic segmentation

### ISSUE THREAD

**Issue by lxxue** [Jumpat/SegAnyGAussians#6]
Hi,

Thanks for the great work. I wonder if there is a way to obtain panoptic segmentation with the learned features?

**Comment by Jumpat** [comment]
Hello! Thanks for your interest! 

SAGA is an interactive segmentation model, which do not support panoptic segmentation naturally. You can modify the code to provide automatic prompts for panoptic segmentation.

For convenience, you may want to check some other good works that support panoptic segmentation. For example, you can try the [Gaussian-Grouping](https://github.com/lkeab/gaussian-grouping) (a concurrent study of SAGA).
