### ISSUE TITLE
environment.yml in v2

### ISSUE THREAD

**Issue by Luca-Wiehe** [Jumpat/SegAnyGAussians#60]
Very nice that you just published the `v2`-version of this repo. I know that you are probably still in the progress of implementing `v2` and the current version isn't final. I just wanted to report some issues I have faced while trying to work with the repo. Maybe it helps you to prioritize your implementation. First of all, I had to move `dearpygui` to the pip section of `environment.yml`. I also had to add some additional dependencies resulting in the following `environment.yml`:
```
name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - hdbscan
  - matplotlib
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/simple-knn
    - third_party/segment-anything
    - dearpygui
    - opencv-python
    - open-clip-torch
    - joblib==1.1.0
```

`joblib==1.1.0` is necessary to successfully import `hdbscan` otherwise [this issue](https://github.com/scikit-learn-contrib/hdbscan/issues/565) occurs.

**Comment by Jumpat** [comment]
Thanks for your reminder! I will modify it.
