### ISSUE TITLE
train_scene.py in v2

### ISSUE THREAD

**Issue by Luca-Wiehe** [Jumpat/SegAnyGAussians#61]
In `train_scene.py`, a mask argument is required. I assume that `'mask'` refers to the `/mask_scales/`-folder from the file-tree you mentioned. To generate these masks, we need a path to our pre-trained model which would be created in `train_scene.py`. Looks like a mutual dependency to me.

Output after `python train_scene.py -s <dataset>`
```
Training progress:   0%|                                                                                                                                                       | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_scene.py", line 230, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_scene.py", line 89, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/<usr>/segment_3d_gaussians/gaussian_renderer/__init__.py", line 97, in render
    cov3D_precomp = cov3D_precomp)
  File "/home/<usr>/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'mask'
```

**Comment by Jumpat** [comment]
Yeah, thanks for your reminder! There is still something that needs to be finished. I will revise them in the following days.

**Comment by Jumpat** [comment]
This error is caused by the modification to the diff_rasterization lib. In this v2 version we deprecate the original mask rendering pipe in the original version, which uses another mask confidence attribute and adapt the diff-rasterizer to it. 

In v2, we use the original diff-rasterizer, so you may need to re-install it.

**Comment by Jumpat** [comment]
We have replaced the wrong diff-rasterizer in submodules, you can pull it down and re-install it.

**Comment by Luca-Wiehe** [comment]
Awesome, it works in the new version!
