### ISSUE TITLE
prompt_segmenting.ipynb in v2

### ISSUE THREAD

**Issue by Luca-Wiehe** [Jumpat/SegAnyGAussians#63]
In `prompt_segmenting.ipynb`, there seem to be some issues remaining. All other scripts worked successfully and the file structure is as intended. 

**1) Results are not being exported to `segmentation_res`-folder**
According to the "Rendering" section of the project's README, outputs of the segmentation pipeline should be stored separately in `./segmentation_res/<name>.pt`. However, no outputs are created when I run the notebook. 

**2) Bugs in Language-driven Segmentation**
2.1. `fixed_scale_gate` in the second cell is undefined
2.2. There are also some issues with sam masks
```
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1911833/333849858.py in <module>
     30         rendered_feature = torch.nn.functional.interpolate(rendered_feature.unsqueeze(0), (feature_h // 4, feature_w // 4), mode = 'bilinear').squeeze()
     31         sam_masks = view.original_masks.cuda().unsqueeze(1)
---> 32         sam_masks = torch.nn.functional.interpolate(sam_masks, (feature_h // 4, feature_w // 4), mode = 'bilinear')
     33 
     34 

~/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/nn/functional.py in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3936         if antialias:
   3937             return torch._C._nn._upsample_bilinear2d_aa(input, output_size, align_corners, scale_factors)
-> 3938         return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
   3939     if input.dim() == 5 and mode == "trilinear":
   3940         assert align_corners is not None

RuntimeError: "upsample_bilinear2d_out_frame" not implemented for 'Bool'
```

**Comment by Jumpat** [comment]
Thanks for pointing out these bugs.

Currently we have added the saving cell to the notebook.

The fixed scale gate is removed.

This inconsistent data type is because that we stored the sam masks as bool to save memory. I add the data type conversion (.float()) to avoid this error.

**Comment by Luca-Wiehe** [comment]
Thanks for taking care of this. I've tried to run the new version and am currently receiving a new error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_2361497/3215542284.py in <module>
      1 flattened_mask_features = torch.cat(seg_features, dim = 0)
----> 2 flattened_clip_features = torch.cat(clip_features, dim = 0)
      3 flattened_clip_features = torch.nn.functional.normalize(flattened_clip_features.float(), dim = -1, p = 2)
      4 flattened_scales = torch.cat(scales, dim = 0)
      5 flattened_mask_identifiers = torch.cat(mask_identifiers, dim = 0).to(torch.float16).cuda()

TypeError: expected Tensor as element 0 in argument 0, but got NoneType
```

It appears that the list of `clip_features` doesn't get populated properly and remains empty. I have extracted clip features before running the notebook but in no point in the notebook did I have to specify the path to clip-features. Is this required somewhere?

**Comment by Jumpat** [comment]
Hi, you need to set 'dataset.need_features = True' in Data and Model Preparation. This is usually disabled to reduce GPU memory overhead.

**Comment by Luca-Wiehe** [comment]
Works like a charme now! Is there a way to export results from language-based segmentation?

**Comment by Jumpat** [comment]
Yeah, you can just use the save method provided in the notebook to save the binary mask.

**Comment by Luca-Wiehe** [comment]
Great, thanks for your support!
