### ISSUE TITLE
Obtaining mask descriptions

### ISSUE THREAD

**Issue by Luca-Wiehe** [Jumpat/SegAnyGAussians#64]
For many semantic segmentation tasks, we want to obtain labels for a whole scene. I.e. in addition to segmentation masks (and an integer describing that they differ), we also want to have a class description of what the masks depicts. In the "Clustering" section of your `prompt_segmenting.ipynb`-notebook, you only visualize masks. Is there a way to also obtain the corresponding class names?

**Comment by Jumpat** [comment]
The clustering is class-agnostic. It is easy to save the corresponding class id for each object, however, it you want to get the category you may need another recognition model like CLIP.
