### ISSUE TITLE
Can anyone explain saga_gui?

### ISSUE THREAD

**Issue by shawnFuu** [Jumpat/SegAnyGAussians#66]
This gui really confused me.
I clicked the clickmode->segment3d->clicked the bottle of the scene->save as precomputed-mask.
![微信图片_20240609122619](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/08b0f7fd-24f3-475b-9297-e472b106427a)
Then
![微信图片_20240609122553](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/6332157e-143d-4650-b45a-5ce8ca85db6c)
it has been "saving as..." for half an hour. I dont know whether it works or not.
Can anyone give me help?I would really appreciate it!

**Comment by Jumpat** [comment]
Hi, the outputted 'saving ...' is only used for debug. In fact the segmentation result have been stored as 'segmentation_res/precomputed_mask.pt'.

**Comment by congwei45** [comment]
How to click the scene? I try to click but no response.

**Comment by shawnFuu** [comment]
> Hi, the outputted 'saving ...' is only used for debug. In fact the segmentation result have been stored as 'segmentation_res/precomputed_mask.pt'.

Thank you! I have found the result
