### ISSUE TITLE
Problem about 3D segmentation

### ISSUE THREAD

**Issue by congwei45** [Jumpat/SegAnyGAussians#69]
Where is the segmented 3D object saved and how can I view it?

**Comment by congwei45** [comment]
And can you explain the usage of saga_gui in detail in the readme?

**Comment by shawnFuu** [comment]
you can see the result in segmentation_res saved as precomputed_mask.pt. However, I didnot get the correct mask with no bac
kground removed.

**Comment by Jumpat** [comment]
The project is still ongoing. We will update the instruction of the GUI usage in the near future.

**Comment by congwei45** [comment]
> The project is still ongoing. We will update the instruction of the GUI usage in the near future.

This gui really confused me.
I clicked the clickmode->clicked the middle of the scene->segment3d->save as precomputed-mask. 
Then the values ​​in the mask I got were all true, and the corresponding target was not segmented. Why is this?

**Comment by Jumpat** [comment]
@congwei45 We have updated the readme file. Hope the added instruction of the GUI interface can help you.
