### ISSUE TITLE
No masks have been found in output/train/ours_30000/mask

### ISSUE THREAD

**Issue by shawnFuu** [Jumpat/SegAnyGAussians#70]
I dont find any mask in the file.
Also, 3D project hasnt been segmented properly in output/train/ours_30000/renders. That means the background hasnot been removed.
![屏幕截图 2024-06-13 124348](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/11356fcf-15e9-4b68-add1-503ec903b6c5)
seen as above.

Sorry to interrupt you again. Maybe I dont make correct segmentation in saga_gui.py, do I? I am looking forward to any help.

**Comment by Jumpat** [comment]
Hi, if you want to get segmented object rendering, you need to run 

> python render.py -m <path to the pre-trained 3DGS model> --precomputed_mask <path to the segmentation results> --target scene --segment

If you want to get the segmentation mask, you need to run

> python render.py -m <path to the pre-trained 3DGS model> --precomputed_mask <path to the segmentation results> --target seg

Note that the '--segment' arg is essential for removing the background.

To get the segmented 3D object, you need to click segment3d in the GUI first.

I may refine the instruction of the GUI in the near future.
