### ISSUE TITLE
unexpected error in saga_gui 

### ISSUE THREAD

**Issue by shawnFuu** [Jumpat/SegAnyGAussians#71]
First, I really appreciate it for your instruction on saga.py. That's really helpful.
However, i have come across the same problem again.
![1](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/60f70c5a-cfa7-4e68-96be-31fcbae5c7d7)
I have clicked the clickmode => clicked the bottle in the scene => segment3d => save as precomputed_mask
Then the tip"you should click segment3d first" was raised. Then I waited for minutes only to find no results exported. This procedure has happend many times.
I donnot know whether the tip means I failed, but I do click the button as the instruction. Thats really confusing for me.
Can anyone give me help or anyone succeed? I am looking forward to any replies!

**Comment by Jumpat** [comment]
Hi. Can you find the ./segmentation_res/precomputed_mask.pt file? This seems a little weird. You can check these [lines](https://github.com/Jumpat/SegAnyGAussians/blob/48cb69bfbaf67581bf5a2099b1b1fccfdaecd790/saga_gui.py#L690) for details. Maybe you can remove the 'try: except:' to find the concrete error.

I doubt that there may be some new bugs since I modified the GUI yesterday. Is your code the latest version?

**Comment by shawnFuu** [comment]
> Hi. Can you find the ./segmentation_res/precomputed_mask.pt file? This seems a little weird. You can check these [lines](https://github.com/Jumpat/SegAnyGAussians/blob/48cb69bfbaf67581bf5a2099b1b1fccfdaecd790/saga_gui.py#L690) for details. Maybe you can remove the 'try: except:' to find the concrete error.
> 
> I doubt that there may be some new bugs since I modified the GUI yesterday. Is your code the latest version?
Thanks! I will try.

**Comment by shawnFuu** [comment]
> Hi. Can you find the ./segmentation_res/precomputed_mask.pt file? This seems a little weird. You can check these [lines](https://github.com/Jumpat/SegAnyGAussians/blob/48cb69bfbaf67581bf5a2099b1b1fccfdaecd790/saga_gui.py#L690) for details. Maybe you can remove the 'try: except:' to find the concrete error.
> 
> I doubt that there may be some new bugs since I modified the GUI yesterday. Is your code the latest version?


Hi. I have found the bugs.
![图片1](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/00f4f197-64e5-492b-8233-eda266ee8dff)
Is it because I havent update the file "GaussianModel"?
I find that there are some difference about these lines between two versions.
![图片2](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/c8ba9b7d-6073-4be5-b546-87b0d5dd32f7)
I wonder why to modify the code in this way.
Sorry to interrupt you again! I am looking forward to your any replies.

**Comment by Jumpat** [comment]
You may need to pull the whole repo to update these dependencies.

This modification aims to align the number of entries of the segmentation binary mask with the number of Gaussians in the whole scene when users conduct multiple times of segmentation.

The segmentation times can trace the latest time of segmentation and maintain the past multiple times of segmentation, which are used for rolling back.

**Comment by shawnFuu** [comment]
> You may need to pull the whole repo to update these dependencies.
> 
> This modification aims to align the number of entries of the segmentation binary mask with the number of Gaussians in the whole scene when users conduct multiple times of segmentation.
> 
> The segmentation times can trace the latest time of segmentation and maintain the past multiple times of segmentation, which are used for rolling back.

Thanks! I succeed!
