### ISSUE TITLE
Errors when training new scene with train_scene.py v2

### ISSUE THREAD

**Issue by Zacharie06** [Jumpat/SegAnyGAussians#72]
I try to train with my own data but got this error: 
raceback (most recent call last):
```
  File "D:\SAGA\SegAnyGAussians\train_scene.py", line 230, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "D:\SAGA\SegAnyGAussians\train_scene.py", line 131, in training
    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
  File "D:\SAGA\SegAnyGAussians\scene\gaussian_model.py", line 568, in densify_and_prune
    self.densify_and_clone(grads, max_grad, extent)
  File "D:\SAGA\SegAnyGAussians\scene\gaussian_model.py", line 562, in densify_and_clone
    self.densification_postfix(new_xyz, new_mask, new_features_dc, new_features_rest, new_opacities, new_scaling, new_rotation)
  File "D:\SAGA\SegAnyGAussians\scene\gaussian_model.py", line 506, in densification_postfix
    self._mask = optimizable_tensors["mask"]
KeyError: 'mask'
```

btw I have installed all submodules.

**Comment by Jumpat** [comment]
Hello

We have removed line 506. You can pull the latest version and try it again.

**Comment by Zacharie06** [comment]
Hi, 
got new error 
```
Traceback (most recent call last):
  File "D:\SAGA\SegAnyGAussians\train_scene.py", line 230, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "D:\SAGA\SegAnyGAussians\train_scene.py", line 131, in training
    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
  File "D:\SAGA\SegAnyGAussians\scene\gaussian_model.py", line 571, in densify_and_prune
    self.densify_and_clone(grads, max_grad, extent)
  File "D:\SAGA\SegAnyGAussians\scene\gaussian_model.py", line 535, in densify_and_split
    new_mask = self._mask[selected_pts_mask].repeat(N,1)
IndexError: The shape of the mask [6851] at index 0 does not match the shape of the indexed tensor [6769] at index 0
```
I also notice that some of the `self._mask ` were commented out. What is the purpose of `self._mask `? 
I add `self._mask = torch.ones((self._xyz.shape[0],), dtype=torch.float, device="cuda")` both in functions `densify_and_clone `and `densify_and_split` now the training can continue

**Comment by Zacharie06** [comment]
BTW, in `extract_segment_everything_masks`  in `parser.add_argument("--downsample", default=1, type=int)` default type is int, but 
line 41` if args.downsample == "1" or args.downsample_type == 'mask':` it checks string "1" which is always false.

**Comment by shawnFuu** [comment]
You can download the initial version of scene/gaussian_model. It works well.

**Comment by Jumpat** [comment]
> You can download the initial version of scene/gaussian_model. It works well.

Using the previous version makes it ok for training but leads to failure in the SAGA gui. I have modified the code, you can update it and re-try.

**Comment by Zacharie06** [comment]
> > You can download the initial version of scene/gaussian_model. It works well.
> 
> Using the previous version makes it ok for training but leads to failure in the SAGA gui. I have modified the code, you can update it and re-try.

After manully setting `self._mask = torch.ones((self._xyz.shape[0],), dtype=torch.float, device="cuda")` I can train 3D GS model now. The result from the GUI looks good, and I can even save the .ply using. 
Great Work!

**Comment by shawnFuu** [comment]
> > You can download the initial version of scene/gaussian_model. It works well.
> 
> Using the previous version makes it ok for training but leads to failure in the SAGA gui. I have modified the code, you can update it and re-try.

Sorry to find new errors again in saving models. 

[ITER 7000] Saving Gaussians [16/06 15:24:39]
Traceback (most recent call last):
  File "train_scene.py", line 230, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_scene.py", line 121, in training
    scene.save(iteration)
  File "/home/fuxiaowen/DLproject/SAGA/scene/__init__.py", line 228, in save
    self.gaussians.save_ply(os.path.join(point_cloud_path, target+"_point_cloud.ply"), has_mask='no_mask' not in target)
  File "/home/fuxiaowen/DLproject/SAGA/scene/gaussian_model.py", line 230, in save_ply
    attributes = np.concatenate((xyz, mask, normals, f_dc, f_rest, opacities, scale, rotation), axis=1) if has_mask else np.concatenate((xyz, normals, f_dc, f_rest, opacities, scale, rotation), axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Comment by Jumpat** [comment]
Sorry to mess up the original code... I will fix it thoroughly...

**Comment by Jumpat** [comment]
Try it again. I have test it on my device locally. I hope it would be okay now. And I think after remove the mask attribute saved in the GS model, the trained model may be directly view in the SIBR viewer.
