### ISSUE TITLE
Trained 3D-GS model cannot be viewed by SIBR Viewer

### ISSUE THREAD

**Issue by Zacharie06** [Jumpat/SegAnyGAussians#73]
![image](https://github.com/Jumpat/SegAnyGAussians/assets/50125565/ccc5863e-1e20-4dbf-b25b-4b012a6627bc)

**Comment by Zacharie06** [comment]
It works with the saga_gui, thx!

**Comment by Jumpat** [comment]
Yeah, there are added attributes in the Gaussian model, thus can not be read by the original GUI. But you can modify the storing logic of the Gaussian model to adapt it to the original SIBR viewer.

**Comment by Zacharie06** [comment]
> Yeah, there are added attributes in the Gaussian model, thus can not be read by the original GUI. But you can modify the storing logic of the Gaussian model to adapt it to the original SIBR viewer.

Thanks mate!
