### ISSUE TITLE
关于这篇工作3D分割的原理

### ISSUE THREAD

**Issue by shawnFuu** [Jumpat/SegAnyGAussians#74]
你好，我非常欣赏你的工作！有一些关于分割原理的问题从阅读文章后我仍不是很清楚。
![00](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/0a74fe2a-a72a-47ef-805d-aeddc43a136a)
对于这样的场景，如果我想要分割出皮卡丘，该工作的方法是倾向于提取只表示皮卡丘的高斯来渲染的，还是全图渲染特征图然后基于特征图做皮卡丘分割？
这个问题对我们的研究非常重要，非常期待你的回复！

**Comment by Jumpat** [comment]
你好，感谢你的关注。
我们的方法可以同时兼容两种形式，但我们更倾向于直接获得期望物体的3D高斯而不是2D分割结果，即你所提到的“提取只表示皮卡丘的高斯来渲染”。

**Comment by shawnFuu** [comment]
> 你好，感谢你的关注。 我们的方法可以同时兼容两种形式，但我们更倾向于直接获得期望物体的3D高斯而不是2D分割结果，即你所提到的“提取只表示皮卡丘的高斯来渲染”。


非常感谢你的回复！但是我从文章的阅读中感觉方法思路更倾向于后者，例如
![微信图片_20240618232736](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/c3c20219-71c2-4a12-8164-a5f62054a460)
![微信图片_20240618232748](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/e10b74f1-8c73-4a80-ac54-d1c15ee51fe3)
![微信图片_20240618232755](https://github.com/Jumpat/SegAnyGAussians/assets/162449599/616631c6-f75c-459e-9243-8ec5a07c2b20)
从上述段落似乎表明对特定物体分割时首先对特定视角下渲染的2d特征图进行分割，是我理解有误吗？
如果是我理解有误，那么按照readme的流程进行分割时的确是提取目标物体的3D高斯再进行渲染吗？

**Comment by Jumpat** [comment]
首先这里指的是通过在二维特征图上获得用来分割的特征向量，即一般意义上的prototype / classifier / prompt / query feature，这个feature进一步被用来和三维高斯上的分割特征相匹配来获得对应的三维高斯。这里的描述是为了指出SAGA支持在二维特定视角下输入prompt来进行三维分割，而不一定需要三维提示词。

另外，请注意我们已经对论文进行了更新，新版论文维持了这个setting，并对应repo中的v2 branch，而这一版本的论文对应的是原来的main branch代码。

**Comment by shawnFuu** [comment]
> 首先这里指的是通过在二维特征图上获得用来分割的特征向量，即一般意义上的prototype / classifier / prompt / query feature，这个feature进一步被用来和三维高斯上的分割特征相匹配来获得对应的三维高斯。这里的描述是为了指出SAGA支持在二维特定视角下输入prompt来进行三维分割，而不一定需要三维提示词。
> 
> 另外，请注意我们已经对论文进行了更新，新版论文维持了这个setting，并对应repo中的v2 branch，而这一版本的论文对应的是原来的main branch代码。


非常感谢！我会仔细查看！
