### ISSUE TITLE
When I enter "get_scale.py," it shows "killed."

### ISSUE THREAD

**Issue by songyuri** [Jumpat/SegAnyGAussians#75]
Hello, thank you for making great code. 
I have a question about a problem that occurs when I run the code. 
When I enter the command "get_scale.py," a strange warning appears, and then the process gets killed. 
Do you have any idea about this issue?

![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/5dbd4a5a-41b6-4083-a68b-c527194d72c3)

Thank you for supporting!

**Comment by Jumpat** [comment]
Hi, this is caused by CPU out of memory. How many masks are there for each image? What is the image size? You may need to downsample the images during mask extraction.

**Comment by songyuri** [comment]
180 images and I did downsample to 4
Is there anything I can do more? 🥲

2024년 6월 19일 (수) 오후 5:28, Jumpat ***@***.***>님이 작성:

**Comment by songyuri** [comment]
(How many masks are there for each image?) << How can I check this? and I took pictures with my iphone11

**Comment by yzslab** [comment]
The `get_scale.py` will load all masks into CPU memory at once:
https://github.com/Jumpat/SegAnyGAussians/blob/ca2ec1416b93f4ddc99383b4c05e6a2bb3734954/get_scale.py#L100-L107

You can change it to load the mask when needed here:
https://github.com/Jumpat/SegAnyGAussians/blob/ca2ec1416b93f4ddc99383b4c05e6a2bb3734954/get_scale.py#L124
e.g.: `corresponding_masks = torch.load(..., map_location="cpu").float()`

**Comment by yzslab** [comment]
Besides, you are likely to meet CUDA OOM when you start training, some extra modifications are also required: https://github.com/Jumpat/SegAnyGAussians/issues/65#issuecomment-2160447443

**Comment by yzslab** [comment]
Or convert to float type when the mask is required:
```diff
diff --git a/get_scale.py b/get_scale.py
--- a/get_scale.py	(revision c1fb52d48db849bfcf69aba999941e772c1825b2)
+++ b/get_scale.py	(date 1718806880843)
@@ -99,12 +99,12 @@
     images_masks = {}
     for i, image_path in tqdm(enumerate(sorted(os.listdir(os.path.join(dataset.source_path, 'images'))))):
         # print(image_path)
-        image = cv2.imread(os.path.join(os.path.join(dataset.source_path, 'images'), image_path))
-        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
+        # image = cv2.imread(os.path.join(os.path.join(dataset.source_path, 'images'), image_path))
+        # image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
         masks = torch.load(os.path.join(os.path.join(dataset.source_path, 'sam_masks'), image_path.replace('jpg', 'pt').replace('JPG', 'pt').replace('png', 'pt')))
         # N_mask, C
 
-        images_masks[image_path.split('.')[0]] = masks.cpu().float()
+        images_masks[image_path.split('.')[0]] = masks.cpu()
 
 
     OUTPUT_DIR = os.path.join(args.image_root, 'mask_scales')
@@ -121,7 +121,7 @@
         depth = rendered_pkg['depth']
 
         # plt.imshow(depth.detach().cpu().squeeze().numpy())
-        corresponding_masks = images_masks[view.image_name]
+        corresponding_masks = images_masks[view.image_name].float()
 
         # generate_grid_index(depth.squeeze())[50, 1]

```

**Comment by songyuri** [comment]
Thank you for kind explanation!

I changed like this:
        corresponding_masks = torch.load(os.path.join(dataset.source_path, 'sam_masks', view.image_name.replace('jpg', 'pt').replace('JPG', 'pt').replace('png', 'pt')), map_location="cpu").float()


I'm sorry, I'm quite new to this field and still very inexperienced.

I wrote it like this with the help of GPT. Is this correct?

**Comment by yzslab** [comment]
> Thank you for kind explanation!
> 
> I changed like this: corresponding_masks = torch.load(os.path.join(dataset.source_path, 'sam_masks', view.image_name.replace('jpg', 'pt').replace('JPG', 'pt').replace('png', 'pt')), map_location="cpu").float()
> 
> I'm sorry, I'm quite new to this field and still very inexperienced.
> 
> I wrote it like this with the help of GPT. Is this correct?

Try this: https://github.com/Jumpat/SegAnyGAussians/issues/75#issuecomment-2178848839

**Comment by songyuri** [comment]
I changed like this
![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/5942acdb-ee6e-4b71-aabc-3b928746a07d)

But still have problems
![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/7efbf6bb-1363-4c6d-80e6-6a2587b9f3d9)


Also I changed down sample to 8

**Comment by songyuri** [comment]
I added the `#` on lines 102 and 103, but the result is still the same 😭

**Comment by yzslab** [comment]
How many memory do you have?
I tested on a scene with 251 images in 1920×1080, without any resizing. It consumes about 45 GB memory during the [version mentioned at #75 (comment)](https://github.com/Jumpat/SegAnyGAussians/issues/75#issuecomment-2178848839) running.

> I added the `#` on lines 102 and 103, but the result is still the same 😭

**Comment by songyuri** [comment]
ahh I tested on 180 images and size is 2160 x 3840 😅

**Comment by songyuri** [comment]
hi I finally solved this problem resizing images thank you so much!
but I have another problem 😭
Do you know about this error?
![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/a1e90de1-79cd-4020-ad05-a6e371dbb7d6)

**Comment by songyuri** [comment]
I finally solved the problems thank you! and I try to run GUI, but have some questions
Can the GUI be run on Ubuntu WSL?
I tried it currently, but I get the following error:
![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/c570752c-a4b2-4407-93d0-fa784f21036c)

**Comment by Jumpat** [comment]
Hi, there are too many images and they are too large.

The GUI error is caused by PCA decomposition. I wonder the shape of ``eigenvalues`` and ``see_chosen``. What is your PyTorch version?

**Comment by songyuri** [comment]
version is 2.0.1 and How can I know about eigenvalues and see_chosen?

**Comment by Jumpat** [comment]
You may need cudatoolkit=11.6 and pytorch=1.12.1

In the update of PyTorch the function may have been changed.

To see the shape about eigenvalues and sem_chosen, you can print(xxx.shape) before the error is raised.

**Comment by yzslab** [comment]
> version is 2.0.1 and How can I know about eigenvalues and see_chosen?

I am using 2.0.1 too. Try this:
```diff
Index: saga_gui.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/saga_gui.py b/saga_gui.py
--- a/saga_gui.py	(revision ca2ec1416b93f4ddc99383b4c05e6a2bb3734954)
+++ b/saga_gui.py	(date 1718867708363)
@@ -549,10 +549,9 @@
         mean = torch.mean(X, dim=0)
         X = X - mean
         covariance_matrix = (1 / n) * torch.matmul(X.T, X).float()  # An old torch bug: matmul float32->float16, 
-        eigenvalues, eigenvectors = torch.eig(covariance_matrix, eigenvectors=True)
-        eigenvalues = torch.norm(eigenvalues, dim=1)
-        idx = torch.argsort(-eigenvalues)
-        eigenvectors = eigenvectors[:, idx]
+        eigenvalues, eigenvectors = torch.linalg.eig(covariance_matrix)
+        idx = torch.argsort(-eigenvalues.real)
+        eigenvectors = eigenvectors.real[:, idx]
         proj_mat = eigenvectors[:, 0:n_components]
         
         return proj_mat
```

**Comment by songyuri** [comment]
omg thank you! I will try it

**Comment by songyuri** [comment]
Glfw Error 65544: X11: Failed to open display 10.255.255.254:0

![image](https://github.com/Jumpat/SegAnyGAussians/assets/69284463/406f58c9-c331-4298-85c9-538cb4be2485)


Has anyone know about this problem? 😭

**Comment by Jumpat** [comment]
This seems not a problem about SAGA. 🥲
Are you running the GUI on a remote server?

**Comment by songyuri** [comment]
I finally run GUI 💅🎉
Thank you everyone 🌸

2024년 6월 20일 (목) 오후 6:41, Jumpat ***@***.***>님이 작성:

**Comment by Jumpat** [comment]
Great!

**Comment by Zhangpeigeng** [comment]
> Glfw Error 65544: X11: Failed to open display 10.255.255.254:0
> 
> ![image](https://private-user-images.githubusercontent.com/69284463/341334685-406f58c9-c331-4298-85c9-538cb4be2485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDE1MTIsIm5iZiI6MTcyMjE0MTIxMiwicGF0aCI6Ii82OTI4NDQ2My8zNDEzMzQ2ODUtNDA2ZjU4YzktYzMzMS00Mjk4LTg1YzktNTM4Y2I0YmUyNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA0MzMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODg3MjkzZmRkZWY3NzMzN2IxZmY4ZDY5MTQ2NzY4MjBjNmFkMGYwOWE3OGU5OTUyZWY3ODdmMWJkMjdkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DRojIhgzjdAcgqNDDCfy5Hh6rrAdSZJcr0VHk8NElRw)
> 
> Has anyone know about this problem? 😭

Hi, I have the same problem here. Could you please explain how did you solve it? Thanks!

**Comment by hyungwoo822** [comment]
@songyuri 
I had same error with you.
![image](https://github.com/user-attachments/assets/825c76c1-68a1-488e-bbca-e078a0db1729)
how did you fix it?
