### ISSUE TITLE
Is this an equation typo?

### ISSUE THREAD

**Issue by yzslab** [Jumpat/SegAnyGAussians#76]
Hi, page 5 of the paper, where the red circle placed:
![image](https://github.com/Jumpat/SegAnyGAussians/assets/564361/fcd829e3-89d1-4a80-99dd-5abaeeed3f08)

**Comment by Jumpat** [comment]
Thanks for raising this up. You are right. This should be s\_{\mathbf{M}\_{\mathbf{I}}^{(j)}}, which denotes the scale of the corresponding mask \mathbf{M}\_{\mathbf{I}}^{(j)}.
