### ISSUE TITLE
关于diff-gaussian-rasterization_contrastive_f的问题

### ISSUE THREAD

**Issue by Doctor-James** [Jumpat/SegAnyGAussians#81]
您好，我将submodules/diff-gaussian-rasterization_contrastive_f/cuda_rasterizer/config_contrastive_f.h中的NUM_CHANNELS从32改为64，会编译不通过，您能给我一些建议吗，我对cuda代码不太熟悉，谢谢

**Comment by Jumpat** [comment]
你好，64维特征是无法编译通过的，因为GPU的share memory最多只能支持40维左右的特征。如果想要支持64维特征需要将对应的变量存储到普通的全局内存中，但这种操作会导致渲染速度大大减慢。

**Comment by yzslab** [comment]
可以尝试用 gsplat，已经实现好了任意维度的特征的支持了: https://docs.gsplat.studio/main/apis/rasterization.html

**Comment by Doctor-James** [comment]
感谢，我尝试一下
