### ISSUE TITLE
关于使用mask作为prompt

### ISSUE THREAD

**Issue by shawnFuu** [Jumpat/SegAnyGAussians#83]
作者你好，我非常认可你们的工作！我想知道这篇工作能否使用目标物体的mask作为promt以得到目标物体的三维效果？
目前来看saga_gui是以click作为prompt来分割物体，暂未看到上述方式的接口。

期待你的回复！

**Comment by yzslab** [comment]
个人看法：有了 mask 的话，可以把被 mask 的像素当作被鼠标点击的像素，然后用同样的算法分割物体

**Comment by shawnFuu** [comment]
> 个人看法：有了 mask 的话，可以把被 mask 的像素当作被鼠标点击的像素，然后用同样的算法分割物体

很好的想法！我正准备尝试去实现！

**Comment by Jumpat** [comment]
是这样的。点作为prompt可以被视为promptable segmentation的一种基元，在此基础上可以实现不同的prompt方式。因此我们没有针对mask以及box进行特定的prompt设计。

**Comment by shawnFuu** [comment]
> 是这样的。点作为prompt可以被视为promptable segmentation的一种基元，在此基础上可以实现不同的prompt方式。因此我们没有针对mask以及box进行特定的prompt设计。

了解了，感谢你的回复
