### ISSUE TITLE
Where is the function segment in class GaussianModel doing in the code?

### ISSUE THREAD

**Issue by shuyueW1991** [Jumpat/SegAnyGAussians#90]
I did not find anywhere that declares this function. Also I noted that there is an empty mask check where the code is directed to `Please run seg.py`. But I cannot see such python script titled as <seg.py>. Can someone do me a favor to help me understand this?

**Comment by Jumpat** [comment]
This function removed the background Gaussians and its related attributes from the model. The remained Gaussians describe the target object you segmented (stored as precomputed_mask.pt, which is a binary mask)

**Comment by shuyueW1991** [comment]
> This function removed the background Gaussians and its related attributes from the model. The remained Gaussians describe the target object you segmented (stored as precomputed_mask.pt, which is a binary mask)

Hi, Jumpat, thanks for your answer. But I am still wondering where its explicit cal is in the project?

**Comment by Jumpat** [comment]
In render.py, with args --segment, the script will call .segment to get the foreground object.
