### ISSUE TITLE
What is `_mask` for in GaussianModel?

### ISSUE THREAD

**Issue by shuyueW1991** [Jumpat/SegAnyGAussians#92]
Now I know that the `segment` is to remove the background point clouds. However, I find the following code (see
https://github.com/Jumpat/SegAnyGAussians/blob/96e5021f2544af95e7705f91ecd8db6bb5cba381/scene/gaussian_model.py#L423 ) hard to understand:

```
self.segment_times += 1
tmp = self._mask[self._mask == self.segment_times]
tmp[mask] += 1
self._mask[self._mask == self.segment_times] = tmp
```
where,  I think `segment_times` records the times of doing segments. But is `_mask` not a binary mask as `mask` in this function? how is it comparable with `segment_times`? Or, what is `_mask` for in GaussianModel?

**Comment by Jumpat** [comment]
This _mask is designed for the SAGA GUI to support interactive segmentation, specifically, the Undo operation. _mask is a counter to trace the current segmentation state and save the previous states.
