### ISSUE TITLE
Why does my process be killed?

### ISSUE THREAD

**Issue by Zhangpeigeng** [Jumpat/SegAnyGAussians#94]
My running process was killed when I run the extract_segment_everything_mask.py. Is it possible that I need to downsample when I get the scale?
<img width="367" alt="Screenshot 2024-07-19 at 12 14 41 PM" src="https://github.com/user-attachments/assets/72ca6004-69bb-4e72-87ee-227b2af9b269">

**Comment by Jumpat** [comment]
This is caused by limited CPU memory. Please refer to [this issue](https://github.com/Jumpat/SegAnyGAussians/issues/75).

**Comment by Zhangpeigeng** [comment]
Thanks. I tried those methods but I still faced the same issue.

**Comment by Zhangpeigeng** [comment]
Thank you so much. I tried those methods and I can run that part. It seems that my desktop performance is limited. After downsizing all the images, this script runs very well. Thanks again!
